#!/usr/bin/python


customized_dico="/usr/local/share/aspell/w3c.dat"
aspell = "/usr/local/bin/aspell"

Page1 ="""Content-Type:text/html


<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en-US" lang="en-US">
<head>
  <title>W3C Dictionary Customizer</title>
  <link rel="stylesheet" href="http://www.w3.org/Stylesheets/base"/>
</head>

<body>
<p><a href="http://www.w3.org"><img src="http://www.w3.org/Icons/w3c_home" alt="W3C"/></a></p>
<h1>W3C Dictionary Customizer</h1>
<h2>Status</h2>
<p>This tool complements the <a href="spellchecker">W3C Spell checker</a> allowing to add words to the W3C dictionary. It's intended to be used by the <a href="http://www.w3.org/Team/">Team only</a>.</p>
"""

Page2 = """
<h2>Adding a word</h2>
<form action="update_dictionary" method="post">
<p><input type="text" name="list[]"/>
<input type="submit" value="Add to the dictionary"/></p>
</form>
<hr/>
<address><a href="http://www.w3.org/People/Dom/">Dominique Haza&euml;l-Massieux</a><br/>
Last Modified: $Date$
</address>

</body>
</html>"""

if __name__ == '__main__':
        import os

        if os.environ.has_key('SCRIPT_NAME'):
                import cgi
                fields = cgi.FieldStorage()
                words_list = []
                print Page1
                if fields.has_key('list[]') and os.environ.has_key('REQUEST_METHOD') and os.environ['REQUEST_METHOD']=='POST':
                        import string
                        print "<h2>Dictionary updated</h2>"
                        words = fields['list[]']
                        if type(words) is type([]):
                                for word in words:
                                        if string.find(word.value,'"')==-1:
                                                words_list.append(word.value)
					elif string.find(words.value,'"')==-1:
						words_list.append(words.value)
			from subprocess import Popen, PIPE
			command = [aspell, "--lang=english", "merge", "personal", customized_dico] + words_list
			po =  Popen(command, stdout=PIPE)
			result = po.communicate()[0]
                        words_list_str = cgi.escape(string.join(words_list))
                        if result==None:
                                print "<p>The following words have been added to the dictionary: %s.</p>" % (words_list_str)
                        else:
                                print "<p>The command %s has terminated abnormaly with output <code>%d</code> The words you submitted (%s) have not been added.</p>" % (cgi.escape(command) , cgi.escape(result), words_list_str)
                print Page2
